# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: 'ts/**/*.ts'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      
    - name: install node
      uses: actions/setup-node@v1.4.2
      with: 
        node-version: 12
    - name: install node modules
      run: npm install
    - name: Typescript compiler
      run: tsc
      
    - name: commit js
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f js/*
        git commit -m "Compiled javascript from typescript"
  
    - name: push commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: action-pr
        
    - name: Initialize Pull Request
      uses:  repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: action-pr
        destination_branch: master
        pr_title: 'Updates javascript files from latest Actions build'
        pr_label: automerge
